---
version: '3.1'
services:
  db:
    image: library/postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
    - ./postgres:/docker-entrypoint-initdb.d:ro
    - ./assets/data:/data:ro
    ports:
    - 5432:5432

  web:
    image: nginx:alpine
    volumes:
    - ./output:/usr/share/nginx/html:ro
    ports:
    - 8080:80